version: '3.8'

services:
  back:
    build: ./back
    container_name: recommendation_back
    ports:
      - "8000:8000"

  front:
    build: ./front
    container_name: recommendation_front
    ports:
      - "8501:8501"
    depends_on:
      - back